name: movies
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  font_awesome_flutter: ^10.4.0
  http: ^0.13.5
  hidable: ^1.0.3
  flutter_dotenv: ^5.0.2
  intl: ^0.18.0
  palette_generator: ^0.3.3+2
  loading_animation_widget: ^1.2.0+4
  animations: ^2.0.7
  page_transition: ^2.0.9
  transparent_image: ^2.0.1
  shared_preferences: ^2.1.0
  cupertino_back_gesture: ^0.1.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  flutter_rating_bar: ^4.0.1
  json_serializable: ^6.6.1
  google_fonts: ^4.0.3
  cached_network_image: ^3.2.3
  youtube_player_flutter: ^8.1.2
  chip_list: ^2.4.3+8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
